### ISSUE TITLE
"Unable to resolve module" - Install issue?

### ISSUE THREAD

**Issue by MattFoley** [joshswan/react-native-globalize#1]
I'm not sure if this is my problem, or something in the dependencies of this project, bit of a JS beginner. I think I have it installed correctly, but the react native packager gives me this error on attempting to load `http://localhost:8081/index.ios.bundle`

```
{"message":"Unable to resolve module cldr-data/supplemental/currencyData.json 
from /Users/tfallon/Documents/testproject/node_modules/react-native-globalize/lib/globalize.js: 
Invalid directory /Users/node_modules/cldr-data/supplemental/currencyData.json",
"name":"UnableToResolveError","type":"UnableToResolveError","errors":[{}]}
```

Seems like something is looking for cldr in some top level node_modules directory, which doesn't exist. I'm running Node 5.4, npm 3.3.12, and the latest React Native. Any idea what could be going wrong here?

Thanks!

**Comment by joshswan** [comment]
Seems to be an issue with the react native packager: https://github.com/facebook/react-native/issues/4968

There are a few fixes suggested in that thread (e.g. kill and restart the packager, clear the cache, etc.). Try giving those a shot and see if it helps.

**Comment by joshswan** [comment]
Closing for now as this seems to be an RN issue. Let me know if there's anything I can do on my end
