### ISSUE TITLE
E_UNSUPPORTED: Unsupported {"feature": "year pattern `u`"}

### ISSUE THREAD

**Issue by sibelius** [joshswan/react-native-globalize#10]
I'm receiving the following error when I try to format a date

```jsx
<FormattedDate
            value={new Date()}
            skeleton="dMy"
            />
```

`skeleton="yMd"` works fine

**Comment by joshswan** [comment]
Skeletons need to be specified in largest to smallest order so `skeleton="yMd"` would be the correct skeleton in this case. The date formatting is then carried out based on norms for that particular language/locale, NOT based on the order of your skeleton.

You can see examples of some formatting options in the documentation for the Globalize library: https://github.com/jquery/globalize/blob/master/doc/api/date/date-formatter.md

**Comment by sibelius** [comment]
thanks for the explanation

yMD -> 11/30/2010

what if I want to display year using only 2 digits instead of 4?

is that possible?

**Comment by joshswan** [comment]
Based on the CLDR [documentation](http://www.unicode.org/reports/tr35/tr35-dates.html#Date_Field_Symbol_Table), `skeleton="yyMd"` should work. However, not all skeletons work as expected: https://github.com/jquery/globalize/issues/271

If not, this will work: `<FormattedDate value={new Date()} date="short" />`. The "presets" on the [date formatter](https://github.com/jquery/globalize/blob/master/doc/api/date/date-formatter.md) page all work just fine.

**Comment by sibelius** [comment]
thanks I'll try that

**Comment by sibelius** [comment]
thanks I'll try that

**Comment by sibelius** [comment]
thanks I'll try that

**Comment by sibelius** [comment]
thanks I'll try that
