### ISSUE TITLE
FormattedMessage: How to change text in upperCase?

### ISSUE THREAD

**Issue by bietkul** [joshswan/react-native-globalize#13]
messages: {
"hello": "Hey"
} 
`<FormattedMessage
   message="hello"
 />`

//HEY

**Comment by joshswan** [comment]
You can use another message key to use the uppercase version when necessary:
```json
{
    "hello": "Hey",
    "helloUpper": "HEY",
}
```
`<FormattedMessage message="helloUpper" />`

Or you can use the message formatter directly and call `toUpperCase()` on the returned string:
```javascript
const text = this.context.globalize.getMessageFormatter('hello')().toUpperCase();
```
