### ISSUE TITLE
Get string without use FormattedMessage

### ISSUE THREAD

**Issue by rafaeljimenez** [joshswan/react-native-globalize#14]
Is it possible to get only the string without use FormattedMessage ?

**Comment by joshswan** [comment]
See: https://github.com/joshswan/react-native-globalize#context

If you've got everything set up correctly, you can make and use message formatters:
```javascript
const formatMessage = this.context.globalize.getMessageFormatter('messageKey');
const message = formatMessage({ name: 'Bob' });
```
