### ISSUE TITLE
Cannot read property 'getCurrencyFormatter' of undefined

### ISSUE THREAD

**Issue by osuthorpe** [joshswan/react-native-globalize#20]
Getting this error: 

Cannot read property 'getCurrencyFormatter' of undefined

FormattedCurrency.render
FormattedCurrency.js:25:50

**Comment by joshswan** [comment]
See #15 & #17. Make sure you've got [FormattedWrapper](https://github.com/joshswan/react-native-globalize#formattedwrapper) or some other context provider at the root of your application.
