### ISSUE TITLE
I Use FormattedWrapper ,How to get multiple languages in non component areas?

### ISSUE THREAD

**Issue by lenglengiOS** [joshswan/react-native-globalize#24]
Hi, i use FormattedWrapper to support multi language,However, normal language can be acquired only in subcomponents.How do I get language from a non child component?Thanks

**Comment by joshswan** [comment]
Again, this is explain in the readme, particularly in the [context](https://github.com/joshswan/react-native-globalize#context) section

**Comment by lenglengiOS** [comment]
Thanks for your time~
