### ISSUE TITLE
Adding prefix

### ISSUE THREAD

**Issue by jmdelatorre** [joshswan/react-native-globalize#26]
Hi,

Is it possible to add a prefix to FormattedNumber or  FormattedCurrency?
I need to add an "%" to the number.

Thanks

**Comment by joshswan** [comment]
This was actually broken due to the `style` prop for styling the `Text` component overriding the `style` prop that allowed you to switch to percent display. I just published `v1.2.0` to npm which allows you to use `numberStyle` with `FormattedNumber`:
```javascript
<FormattedNumber
  value={0.5}
  numberStyle="percent"
/>
// 50%
```

**Comment by jmdelatorre** [comment]
perfect! Worked as intended

I do have another question, what if I would like to add "USD" (as in US dollar). Is there an easy way? such as adding a prefix?

Thanks!

**Comment by joshswan** [comment]
If you want that instead of the symbol, it's pretty easy now that `numberStyle` has been added to `FormattedCurrency` as well:
```javascript
<FormattedCurrency
  value={20}
  numberStyle="code"
/>
// 20 USD
```
But if you want the symbol as well, you'll have to add the currency code yourself.

**Comment by jmdelatorre** [comment]
where do I have to add the currency code? Sorry if its a noob question

**Comment by joshswan** [comment]
I meant you'd have to do something like:
```javascript
<FormattedCurrency value={20} />
<Text>USD</Text>
// $20 USD
```
The currency needs to be set on `FormattedWrapper` or `FormattedCurrency` so you should have access to it.
