### ISSUE TITLE
Cldrjs errors with React 0.26.2

### ISSUE THREAD

**Issue by mikelambert** [joshswan/react-native-globalize#3]
My project works with 0.25 (thanks for the recent fixes!), but upgrading to 0.26.2 (with react 15.0.2), I get a different set of problems:

```
Cannot read property 'init' of undefined

<unknown>
  event.js @ 547:0: superInit = Cldr.prototype.init;
pathNormalize
  event.js @ 22:0: module.exports = factory( require( "cldrjs" ) );
<unknown>
  event.js @ 25:0: factory( Cldr );
loadModuleImplementation
  require.js @ 100:0:  ....
...more require.js...
<unknown>
  node_main.js @ 20:0: require( "./cldr/event" );
...more require.js...
```

Looks like importing `cldrjs` imports `node_main.js` imports `cldr/event.js` imports `cldrjs` (which is technically a cycle). In theory the fact that `node_main.js` sets `module.exports` before importing `cldr/event.js` should help?

Regardless, when `node_main.js` sets module.exports, it is a valid `Cldrjs` class object. Unfortunately, when `cldr/event.js` imports it via `cldrjs`, it is an empty object. I have no idea why this is, or why this apparently changed when I upgraded from react-native 0.25.x to 0.26.2.

It also looks to be entirely within cldrjs, but again given that it's the react-native upgrade is triggering this problem, I doubt the cldrjs folks will care much about the problem. So I'm filing it here in react-native-globalize, as that's the import that manifests itself to me and the border between cldrjs and RN.

**Comment by joshswan** [comment]
Thanks for the detailed info! I just upgraded one of my projects to v0.26.2 and am getting the same error. I think I've found a solution, which I'll try to get released in the next few hours, assuming it works :).

**Comment by joshswan** [comment]
Just published v0.6.0 to npm with a fix. Let me know how it works for you!

**Comment by mikelambert** [comment]
Works for me, thanks! I see you branched out cldrjs yourself...good luck with that, hope you're able to upstream a fix eventually (maybe cldrjs team will have some good ideas on circular dependencies).

Which also reminds me I need to upstream some of my react-native-globalize changes to you...then I can have contributed to both autolink and globalize, hah!

**Comment by joshswan** [comment]
Thankfully cldrjs and globalize both change so slowly that merging in their changes should be easy... Though I'm definitely going to try to make a case for merging the fixes in upstream, especially since I can see no good reason for the circular dependency in the first place.

Looking forward to checking out some PRs!

**Comment by rxaviers** [comment]
Cldrjs `0.4.8` updated with such fix. Please, try using it and If you find any trouble, just let me know.

**Comment by joshswan** [comment]
Thanks for those fixes @rxaviers. It seems to work. I'll update this package during the week
