### ISSUE TITLE
 Cannot read property 'getPluralGenerator' of undefined

### ISSUE THREAD

**Issue by AlmogRnD** [joshswan/react-native-globalize#30]
I'm getting the following error " Cannot read property 'getPluralGenerator' of undefined" 

```
<FormattedPlural
                                        value={0}
                                        zero={<Text>Photo(</Text>}
                                        other={<Text>Photos</Text>} />
```

**Comment by joshswan** [comment]
Have you included `FormattedWrapper` at the root of your app? The code you're showing is fine, but I'd need to see more to have any other suggestions.

**Comment by AlmogRnD** [comment]
Yes I did, I went with a different package
