### ISSUE TITLE
Support for RN49

### ISSUE THREAD

**Issue by beormalte** [joshswan/react-native-globalize#31]
moment/moment error
https://github.com/moment/moment/pull/4187#issuecomment-334423040

**Comment by joshswan** [comment]
Not seeing any issues on RN 0.49.3. Please post the error you're seeing and a code example that causes it.

**Comment by beormalte** [comment]
sorry Josh, you are right, this one's on me. 

I was getting this error
TransformError: /.../moment/moment.js: require() must have a single string literal argument.

Maybe my compiler wasn't feeling it or something.

Thanks anyway
