### ISSUE TITLE
What format is supported for a cldr json file?

### ISSUE THREAD

**Issue by parthgandhi7** [joshswan/react-native-globalize#33]
I actually wanted to use INR also along with the default currencies supported by your package. I think i would be able to pass INR as currency to the cldr props of the [FormattedWrapper](https://github.com/joshswan/react-native-globalize#formattedwrapper). Can you please share an example of an acceptable json file for the cldr array? Or suggest any other good way of doing it?
Thanks

**Comment by joshswan** [comment]
INR isn't included among the default currencies as documented on the README. To customize the locales and currencies, follow the instructions there for creating your own CLDR file:

Edit the two arrays in `gulpfile.js` to suit your needs, run `gulp cldr`, and you've got your own custom version with only what you need.

**Comment by parthgandhi7** [comment]
Yeah, i already did that and i am using my fork directly as the npm module . I though the cldr prop of the FormattedWrapper accepted some kind of array or something. But anyways its working fine with my fork.

**Comment by joshswan** [comment]
Yes, `FormattedWrapper` accepts a `cldr` prop that you can use to load additional CLDR data. So as an alternative, you could have used the above method to generate a CLDR file including the parts you needed that are not included in the default bundle, and then loaded that resulting file into the `cldr` prop. The upside of this method is that you can continue using the standard npm package, but the downside is that you load a lot of CLDR data that you probably don't need.
