### ISSUE TITLE
Ability to use the "alt narrow" currency symbol

### ISSUE THREAD

**Issue by asgeo1** [joshswan/react-native-globalize#34]
When I look in the CLDR json data, there is both `symbol` and `symbol-alt-narrow` keys
					
					"AUD": {
						"displayName": "Australian Dollar",
						"displayName-count-one": "Australian dollar",
						"displayName-count-other": "Australian dollars",
						"symbol": "A$",
						"symbol-alt-narrow": "$"
					},
					"THB": {
						"displayName": "Thai Baht",
						"displayName-count-one": "Thai baht",
						"displayName-count-other": "Thai baht",
						"symbol": "THB",
						"symbol-alt-narrow": "฿"
					},
					"USD": {
						"displayName": "US Dollar",
						"displayName-count-one": "US dollar",
						"displayName-count-other": "US dollars",
						"symbol": "$",
						"symbol-alt-narrow": "$"
					}

I want to print the currency using this format:     `$23.00 USD`.  But at the moment I have to add the USD bit myself...

But it comes out looking silly for Thai  `THB 23.00 THB`,  or Australian  `A$23.00 AUD`.

It would be good if you had an option to print the currency using the `symbol-alt-narrow` key instead of the `symbol` key. 

What do you think?

**Comment by joshswan** [comment]
Totally agree. There's an issue and related PR waiting to be merged over in the globalize repo: https://github.com/globalizejs/globalize/issues/479. Once that lands, this repo can be updated to support the narrow currency symbol.

In the meantime, you could create a map of the symbols of currencies you're using and do the prefix manually, i.e.:
```javascript
const symbols = {
  THB: '฿',
  USD: '$',
  // ...
};

<span>{symbols[currency]}</span>
<FormattedCurrency
  currency={currency}
  numberStyle="code"
  value={23}
/>
// $23.00 USD
// ฿23.00 THB
```
Not ideal, but it'll be consistent until the PR lands.

**Comment by asgeo1** [comment]
Awesome thanks, I've done something like that for now.
