### ISSUE TITLE
Add Locales & Currencies

### ISSUE THREAD

**Issue by azwar** [joshswan/react-native-globalize#35]
Hi, how to add Locales & Currencies? I want to add Currencies of my country.

Thanks.

**Comment by joshswan** [comment]
If you just want to add more locales and currencies to what is already included see the [`Globalize.load`](https://github.com/joshswan/react-native-globalize#globalize) method. If you want to only load a customized set of locales and currencies, follow the instructions under ["Want to customize the included locales and/or currencies?"](https://github.com/joshswan/react-native-globalize#how-does-it-work).
