### ISSUE TITLE
Currency Digits

### ISSUE THREAD

**Issue by ammichael** [joshswan/react-native-globalize#4]
Hello!

Is there any way to set the digits? I noticed it just accept float/integer, so I can't use "toFixed()".
Also, it can't bet set globally. Sometimes I need 2 digits, and sometimes no digits at all.

Thanks!

**Comment by joshswan** [comment]
The `minimumFractionDigits` and `maximumFractionDigits` options are what you're looking for. You should be able to pass those in the options object if you're using `getCurrencyFormatter` (e.g. `this.context.globalize.getCurrencyFormatter('USD', {minimumFractionDigits: 0, maximumFractionDigits: 0})` or via props if you're using the `FormattedCurrency` component (e.g. `<FormattedCurrency minimumFractionDigits={0} maximumFractionDigits={0} value={1.00} />`).

Let me know how that works.

**Comment by ammichael** [comment]
Works perfectly!

Thank you!

So easy.. Did I miss it in docs?!

**Comment by joshswan** [comment]
You didn't miss anything. The globalize library (with some tweaks) is used under-the-hood and their [docs](https://github.com/jquery/globalize) go into extensive detail about all the options available. There's a note at the end of the README but I should probably make that a bit more obvious :)
