### ISSUE TITLE
Is there a way this library can detect the locale automatically?

### ISSUE THREAD

**Issue by chetstone** [joshswan/react-native-globalize#42]
The reason I would want to use something like this is to format numbers according to the user's locale.
But the example in the README shows the locale being explicitly set at the root of the application. This doesn't seem to be very useful IMO.

```
<FormattedProvider locale="en"
```
I must be missing something...

**Comment by joshswan** [comment]
The example there is perhaps a bit too simplistic. While the locale needs to be set on `FormattedProvider`, you can set/update it dynamically. That way, when the locale/currency is changed, all of your formatted text will update as well. For example, if you had the current locale in redux state:
```javascript
class MyApp extends PureComponent {
  render() {
    return (
      <FormattedProvider
        locale={this.props.locale}
        currency={this.props.currency}
        messages={Messages}
      >
        <App />
      </FormattedProvider>
    )
  }
}

export default connect(state => ({
  currency: getCurrencyFromState(state),
  locale: getLocaleFromState(state),
}))(MyApp);
```
Most likely you want to start off by setting the locale according to the user's device settings, for which I'd recommend using something like [react-native-languages](https://github.com/react-community/react-native-languages).

**Comment by chetstone** [comment]
Very helpful. Thanks!
