### ISSUE TITLE
gulp cldr error

### ISSUE THREAD

**Issue by sunaryohadi** [joshswan/react-native-globalize#44]
I am forking the repo and run 'gulp cldr', with
```
const locales = [
  'en',           // English (United States)
  'id'           // Indonesian
];

const currencies = [
  'IDR'          // Indonesia Rupiah
];
```
But, got an error "TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be one of type string or Buffer. Received type undefined".

![Screen Shot 2019-03-09 at 17 05 58](https://user-images.githubusercontent.com/2224395/54069941-0056f980-428e-11e9-9483-bb885403dfe6.png)

How to resolve this?

**Comment by joshswan** [comment]
The gulpfile has been fixed on master. That should solve the problem
