### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by fend25** [joshswan/react-native-globalize#47]
Hello.

Thank you for the project, it is a really necessary one.

As I can see, this project doesn't provide typings and there is no according `@types/react-native-globalize` package.

Do you plan to add typescript typings?

**Comment by joshswan** [comment]
Yep, I'm actively working on a TypeScript rewrite

**Comment by fend25** [comment]
I could help if you'd prefer.

**Comment by joshswan** [comment]
The initial TypeScript rewrite and internal migration to hooks is on `master` already. Things I still want to get to for v4:
- add `withGlobalize` HOC back to make upgrades easier
- formatter hooks (e.g. `const formatter = useDateFormatter(options)`), which will require moving some of the logic out of the components and into the `Globalize` class methods or the hooks themselves
- improvements to the CLDR data bundling (still testing some options)
- docs (changes, migration guide, and general improvements) - thinking of doing a simple docs site to make everything easier to reference

Totally open to any feedback/PRs/etc., just be aware that things may change rapidly 😀

**Comment by joshswan** [comment]
v4 has been released with TypeScript types, a `useGlobalize` hook, simpler formatting functions (e.g. `const { formatDate } = useGlobalize();`), and CLDR data for all locales with completely customizable loading. Check out the migration guide and the rest of the revamped docs for more info :)
