### ISSUE TITLE
typing of `useGlobalize().formatMessage`

### ISSUE THREAD

**Issue by fend25** [joshswan/react-native-globalize#53]
Hello!

Thank you very much for the new version with hooks and typings!

There is one obscurity with typing of `formatMessage`. Typings say that the values object has to contain values of type `string` or `ReactElement`:

https://github.com/joshswan/react-native-globalize/blob/f27ba1553caf84da4d3b1c9444f5091333cc2d80/src/globalize/types.ts#L136
https://github.com/joshswan/react-native-globalize/blob/f27ba1553caf84da4d3b1c9444f5091333cc2d80/src/globalize/types.ts#L141

But docs provide an example with number:
```js
formatMessage('party/guests', {
  count: 1,
  formattedCount: formatNumber(1),
});
```
https://github.com/joshswan/react-native-globalize/blob/f27ba1553caf84da4d3b1c9444f5091333cc2d80/docs/api/formatMessage.md#L125

I am not sure which types could be valid for the `values` values, so I can't provide a good PR. But I could do it, I am just not sure that adding `number` type is enough.

Thank you.

**Comment by joshswan** [comment]
Good catch. Fix released in v4.1.1 :)
