### ISSUE TITLE
getCurrencySymbol() with GlobalizeProvider throwing TypeError

### ISSUE THREAD

**Issue by gstcyr** [joshswan/react-native-globalize#55]
It would be nice if when `getCurrencySymbol` is called with no arguments it would use the locale and currency loaded with GlobalizeProvider. Currently calling it with no arguments give the following error:

```TypeError: Cannot read property 'symbol' of undefined
getCurrencySymbol
node_modules/react-native-globalize/dist/globalize/utils.js:40
  37 |     }
  38 |     const { currencies } = Cldr._raw.main[locale].numbers;
  39 |     const key = altNarrow ? 'symbol-alt-narrow' : 'symbol';
> 40 |     return ((_a = currencies) === null || _a === void 0 ? void 0 : _a[currencyCode][key]) || null;
  41 | }
  42 | export function logError(message, exception) {
  43 |     if (process.env.NODE_ENV !== 'production') {
```

**Comment by joshswan** [comment]
Nice usability improvement! Should work now in v4.3.1 that was just published.

**Comment by gstcyr** [comment]
That was quick! Thanks :)

**Comment by gstcyr** [comment]
On an unrelated note, is it possible to have formattedCurrency use localized Number formatting? ie: 1.000,00  vs  1,000.00

**Comment by joshswan** [comment]
I think you might have deleted the comment, but just in case,
`formatCurrency` should already be using localized number formatting (e.g.
with locale "de" and currencyCode "EUR": `globalize.formatCurrency(4000)`
returns `4.000,00 €`).

If you're seeing anything amiss, just open up an issue :)

**Comment by gstcyr** [comment]
Haha yes thanks figured it out not long after I posted the question.
