### ISSUE TITLE
How to use useGlobalize with  class component

### ISSUE THREAD

**Issue by lewatt23** [joshswan/react-native-globalize#56]
Hello thanks for building this library, please I was wondering is there is a way to use with  **use globalized**, with class component given that I already code the whole application using class component and am just trying to add multilanguage support and I can't convert my whole app to into functional component. 

Thanks

**Comment by lewatt23** [comment]
NVM  found it!!  thanks

**Comment by ugrdursun** [comment]
> Hello thanks for building this library, please I was wondering is there is a way to use with **use globalized**, with class component given that I already code the whole application using class component and am just trying to add multilanguage support and I can't convert my whole app to into functional component.
> 
> Thanks

Hello, how did you solve this ?

**Comment by lewatt23** [comment]
> > Hello thanks for building this library, please I was wondering is there is a way to use with **use globalized**, with class component given that I already code the whole application using class component and am just trying to add multilanguage support and I can't convert my whole app to into functional component.
> > Thanks
> 
> Hello, how did you solve this ?

https://github.com/joshswan/react-native-globalize/blob/master/docs/components/FormattedMessage.md
Here is the class component versions
