### ISSUE TITLE
formatCurrency always return Error value must be anumber 

### ISSUE THREAD

**Issue by atteia** [joshswan/react-native-globalize#57]
Hello 

I tried to use formatCurrency from useGlobalize 

`{formatCurrency(product.price, state.currency)`
also tried 
`{formatCurrency(parseInt(product.price), user.currency)`

also tried 

```
import { FormattedCurrency } from 'react-native-globalize';

const ExampleComponent = () => (
  <FormattedCurrency value={parseInt(product.price)} currency={user.currency} />
);

```

all of them retuned same Error !

could you help with this issue ?

**Comment by joshswan** [comment]
Without details on what error you're seeing and what the values of the various variables in your examples are, it's hard to be of much help. My guess is you haven't configured `GlobalizeProvider`. See the docs for info.

**Comment by atteia** [comment]
my provider is configured as below 
```
 return <GlobalizeProvider locale={lang2Code(user.language)} currency={user.currency}>
                                  <AppRoutes />
                            </GlobalizeProvider>
```

also `formateDate` not working and give same error 

should I use `loadCldr` function ?

**Comment by joshswan** [comment]
Yes, you need to load the locales you need to support using `loadCldr` and have `GlobalizeProvider` in place to be able to use any of the formatting functions. See the [docs](https://github.com/joshswan/react-native-globalize/blob/master/docs/getting-started.md#locale-data) for more info.

**Comment by joshswan** [comment]
Additionally, if you're still having issues, please share a more complete code sample. After following the setup docs, the following code should work:
```javascript
const globalize = useGlobalize();
const formatted = globalize.formatCurrency(10);
// With "en" and "USD", formatted is "$10.00"
```
Note: The error message in the title indicates you're not passing a number to `formatCurrency` so confirm the value you're passing to the function.

**Comment by atteia** [comment]
Thanks it works now the problem was I didn't use `loadCldr` before .
