### ISSUE TITLE
Customizing Formatted Currency Component

### ISSUE THREAD

**Issue by ugrdursun** [joshswan/react-native-globalize#62]
Hello,

First of all thanks for this beautiful library.

I wonder if there is anyway to customize formatted currency component, what I want is;

Normally it gives an output like this:

`$1,000.99`

I want to move symbol to the end with a space like this (at least in my country, at TR it shown like this):

`1,000.99 $`

Also it shows negative numbers as this currently:

`-$1,000.99`

It should be like this at least:

`-1,000.99 $`

Is there any customization supported like this ? Could not find on docs.

Thanks.

**Comment by joshswan** [comment]
Seems like this is a known CLDR issue: https://unicode-org.atlassian.net/browse/CLDR-14070

Until it's fixed, you could potentially format as a number instead of currency and then use `getCurrencySymbol()` to customize how that's displayed.

**Comment by ugrdursun** [comment]
> Seems like this is a known CLDR issue: https://unicode-org.atlassian.net/browse/CLDR-14070
> 
> Until it's fixed, you could potentially format as a number instead of currency and then use `getCurrencySymbol()` to customize how that's displayed.

Thank you so much
