### ISSUE TITLE
Translate functions strings

### ISSUE THREAD

**Issue by lewatt23** [joshswan/react-native-globalize#64]
Hello thanks for this package, But i was wondering how i could use this package in a  non functional  component, such as schema. example 

```
export const transacrionValidationSchema = yup.object().shape({
  phone: yup.string(),
  amount: yup
    .number()
    .min(500, ({min}) => `Le montant doit être d'au moins ${min} XFA`)
    .required('montant est requis'),
});
```

**Comment by joshswan** [comment]
You can access the underlying Globalize object by passing a ref to GlobalizeProvider (see [docs](docs/ref-usage.md)).

If the configured language is expected to change while the app is running, you'll also want to call the formatting methods when the schema runs, not when it builds, or you'll end up with error messages in the previously configured language.
