### ISSUE TITLE
Access functions outside components

### ISSUE THREAD

**Issue by KinanKazmi** [joshswan/react-native-globalize#65]
Hi!
I'm updating + refactoring an old app of mine and i came across the following function. I updated this library to version 4.5.1 but I cant seem to be able to make this function work. The function is outside any class component, in an external JS utility file. It used to work fine in the older version. I call this in multiple places across the app, so i dont actually want to create Globalize components and pass its ref from all the places. Please mention how i can replace this with minimum code changes. Thanks!

// at the start of the file
`
import {Globalize} from 'react-native-globalize';
`
// the function
`
export const globalizeNumber = (num) => {
	const instance = new Globalize(locale, 'USD', {fallback: true});
	const formatNumber = instance.getNumberFormatter({
		minimumIntegerDigits: 1,
		minimumFractionDigits: 2,
		maximumFractionDigits: 2,
	});
	return formatNumber(parseFloat(num));
};
`

**Comment by joshswan** [comment]
Should actually be a bit simpler now:
```typescript
import { createGlobalize } from 'react-native-globalize';

export const globalizeNumber = (num) => {
  const globalize = createGlobalize({ locale, currencyCode: 'USD', fallback: true });
  return globalize.formatNumber(parseFloat(num), { minimumIntegerDigits: 1, minimumFractionDigits: 2, maximumFractionDigits: 2 });
};
```

Depending on how you're managing locales, you can also just do `export const globalize = createGlobalize({ ... });` and import/use that directly wherever. Avoids recreating the instance and formatters each time the function is called.

**Comment by KinanKazmi** [comment]
It works great! Thanks!
