### ISSUE TITLE
On demand loading of locales in a web app

### ISSUE THREAD

**Issue by Cristi6** [joshswan/react-native-globalize#66]
Hi there,

I'm using the same approach as in the Advanced documentation, I have an object like this: 
```
const localeLoaders = {
  de: () => loadCldr(require('react-native-globalize/locale-data/de')),
  en: () => loadCldr(require('react-native-globalize/locale-data/en')),
  es: () => loadCldr(require('react-native-globalize/locale-data/es')),
};
```

and then I have this to change the locale.

```
const [locale, setLocale] = React.useState('en');

React.useEffect(() => {
        const selectedLanguageBundle = localeLoaders[props.languageCode];

         selectedLanguageBundle();
         setLocale(formattedLanguageCode);
    }, [props.languageCode]);

return <GlobalizeProvider locale={locale}>{props.children}</GlobalizeProvider>
```

Everything works well but I noticed that every loadCldr(require('react-native-globalize/locale-data/...')) I place in the localeLoaders object gets added to the final app bundle. In my case I try to use a lot of them since our target are users all around the world and it adds 7MB to the bundle which makes the first app load slow.

I've tried using a template string but that just adds to the final bundle every single locale, adding around 20MB+ to the final app bundle.

Am I missing something? Or is there a way to load them only when needed in my web app?

**Comment by joshswan** [comment]
Those instructions are for a React Native app where you probably want them in the bundle in case the user is offline or whatever. The goal there is to just avoid parsing those files on startup but still include them.

For a web app, you probably want to use `import('react-native-globalize/locale-data/de').then((cldr) => loadCldr(cldr))` (or similar depending on your setup). That would keep the files out of the initial bundle and allow you to load them separately as needed.

**Comment by Cristi6** [comment]
Works perfect. Thank you!
