### ISSUE TITLE
Unable to resolve "../../../../../globalize"

### ISSUE THREAD

**Issue by PierreBresson** [joshswan/react-native-globalize#68]
Hi,

I'm currently updated in the process of updating NMF.earth app to newer expo version (46) with react-native v0.69.6
I can run the app correctly on iOS, but I get the following issue on Android:

```
Android Bundling failed 436ms
Unable to resolve "../../../../../globalize" from "node_modules/react-native-globalize/dist/globalize/formatters/index.js"
```

![Screenshot_1667072269](https://user-images.githubusercontent.com/8709134/198849888-3461a769-cba9-4c62-b57b-06ea424bb337.png)

The error is happening on [chore/expo-update branch](https://github.com/NMF-earth/nmf-app/tree/chore/expo-update).

I've tried to clean yarn cache, delete node_modules and yarn, restart my computer but the problem persist. 
Any idea why?

I'm using react-native-globalize version 4.5.1

**Comment by joshswan** [comment]
I believe you've got an import conflict between the `Globalize.ts` file in the root of your project and the package named `globalize` in node_modules (which react-native-globalize imports).

Renaming that file and clearing expo's cache (`-c`) allows me to build your app successfully.

**Comment by PierreBresson** [comment]
Indeed, thanks ;)
