### ISSUE TITLE
Packager TimeoutError

### ISSUE THREAD

**Issue by ammichael** [joshswan/react-native-globalize#8]
Hello there!

I've been using rn-globabalize for a while, and it worked fine, but suddenly I can't start my app, and the react native packager is throwing this error:

```
Error: TimeoutError: transforming /Users/michael/dev/finances_pro/node_modules/react-native-globalize/lib/cldr.json took longer than 301 seconds.
You can adjust timeout via the 'transformTimeoutInterval' option
    at index.js:101:30
    at tryCallOne (/Users/michael/dev/finances_pro/node_modules/promise/lib/core.js:37:12)
    at /Users/michael/dev/finances_pro/node_modules/promise/lib/core.js:123:15
    at flush (/Users/michael/dev/finances_pro/node_modules/asap/raw.js:50:29)
    at _combinedTickCallback (node.js:376:9)
    at process._tickCallback (node.js:407:11)
```

I've changed nothing about the package, tried to update it but no lucky. When I removed all references to it in my code, the package runs fine.

For reference, I'm using React Native 0.25.1

**Comment by joshswan** [comment]
Hm. I'm running RN 0.26.2 and not having any issues. What version of Node are you running?

**Comment by ammichael** [comment]
Weird =(

Node 3.7.3

**Comment by joshswan** [comment]
I was able to reproduce using Node v5.9.1 (npm 3.7.3) - I'm running v4.4.5 and it's still working fine.

I found a couple of issues that mention this though, leading me to believe it's a packager issue:
https://github.com/facebook/react-native/issues/2795
https://github.com/facebook/react-native/issues/8475

Maybe try using the smaller cldr.json file from `master` to see if it'll work.

**Comment by ammichael** [comment]
Ops, sorry. Yeah, you are right. I was using Node 5.9.1, npm 3.7.3. I just updated everything and now I'm at Node 6.2.2, npm 3.10.3, and still got the issue.

Actually, a little bit different error this time:

```
transformed 668/669 (100%)[node-haste] Encountered an error while persisting cache:
> Error: TimeoutError: transforming /Users/michael/dev/finances_pro/node_modules/react-native-globalize/lib/cldr.json took longer than 301 seconds.
> You can adjust timeout via the 'transformTimeoutInterval' option
>     at index.js:101:30
>     at tryCallOne (/Users/michael/dev/finances_pro/node_modules/promise/lib/core.js:37:12)
>     at /Users/michael/dev/finances_pro/node_modules/promise/lib/core.js:123:15
>     at flush (/Users/michael/dev/finances_pro/node_modules/asap/raw.js:50:29)
>     at _combinedTickCallback (internal/process/next_tick.js:67:7)
>     at process._tickCallback (internal/process/next_tick.js:98:9)
Error: TimeoutError: transforming /Users/michael/dev/finances_pro/node_modules/react-native-globalize/lib/cldr.json took longer than 301 seconds.
You can adjust timeout via the 'transformTimeoutInterval' option
    at index.js:101:30
    at tryCallOne (/Users/michael/dev/finances_pro/node_modules/promise/lib/core.js:37:12)
    at /Users/michael/dev/finances_pro/node_modules/promise/lib/core.js:123:15
    at flush (/Users/michael/dev/finances_pro/node_modules/asap/raw.js:50:29)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

Gonna try to use the smaller cldr.json and I'll update here.

**Comment by joshswan** [comment]
Easiest way is to just fork this repo and tweak `gulpfile.js` to suit your needs. There's an array of languages and currencies near the top that control what gets included in the output. Then just run `gulp cldr` and the resulting file will be placed in `src/cldr.json`. You can just copy that to your project at that point.

Seems like the packager has an issue with large files. Will keep an eye on it. Thanks for reporting this!
